### ISSUE TITLE
Read

### ISSUE THREAD

**Issue by robertoalmeida** [RealTadango/ssensors#26]
I'm trying to collect rpm from a cdi rcexl, but when inserting some lines in the code, the report sport to the receiver stops working.

```
#include <SPort.h>
#define PINO_SPORT 4
#define SENSOR_RPM 0x0500
#define SENSOR_ID 0x12
//
int cdi = 6;
long interval;
//
SPortHub hub(SENSOR_ID, PINO_SPORT);
SimpleSPortSensor sensor_rpm(SENSOR_RPM);
//
void setup() {
  pinMode(cdi, INPUT_PULLUP);
  hub.registerSensor(sensor_rpm);
  hub.begin();
}

void loop() {
  int rpm = 0;
  interval = pulseIn(cdi, HIGH) + pulseIn(cdi, LOW);
  int rps = 1000000UL / interval;
  if ((rps == -1) or ((rps * 60) > 11000)) {
    rpm = 0;
  } else {
    rpm = (rps * 60);
  }
  delay(5);
  sensor_rpm.value = rpm;
  hub.handle();
}
```
I already identified that when commenting the lines the receiver can collect the rpm=0 information

How could I make this work?

```
 interval = pulseIn(cdi, HIGH) + pulseIn(cdi, LOW);
   int rps = 1000000UL / interval;
```

**Comment by robertoalmeida** [comment]
Is this project dead?

**Comment by hmeijdam** [comment]
I think the project is sort of finished. The library works as it was intended.
If your question is more about generic programming, how to make a non blocking routine for reading of pulsefrequency and or pulsewidth, you may try the Arduino forum. They have area's for those kinds of questions.
As far as I know PulseIn is a blocking function, and I also see a delay (5); 
I have learned that the S-port protocol does not like delays, as the answer to polling needs to be almost instant.

**Comment by RealTadango** [comment]
Not dead, i don't have much time to respond. And indeed, pulseIn is blocking. The loop must be very fast for this library to work.

**Comment by robertoalmeida** [comment]
Is there any way for pulseIn to work with this library?

**Comment by RealTadango** [comment]
No. You can use interrupts for you measurement.
